include:
  - project: 'mthreads-ci-templates'
    ref: 'master'
    files:
      - '.base.yml'
      - '.install-musa.yml'

variables:
  MUSA_PATH: "/usr/local/musa/bin"

.build-tilelang_musa-base:
  extends: ".k8s-base"
  needsSourceCode:
    fetch: true
    submodules: false
  timeout: 60m
  variables:
    MUSA_PATH: "${MUSA_PATH:-/usr/local/musa/bin}"
    K8S_IMAGE: "sh-harbor.mthreads.com/os-build/mt-build:developv2"   
    GIT_SUBMODULE_STRATEGY: none

# 构建 Release 版本
build-PH1:
  extends:
    - ".build-tilelang_musa-base"
    - ".install-musa"
  variables:
    MUSA_MODULE: 'MUSATOOLKITS'
  withCredentials:
    - type: git
      id: sh-code
  script:
    - "export PATH=/opt/_internal/cpython-3.10.19/bin:$PATH"
    - "export LD_LIBRARY_PATH=/usr/local/musa/lib:$LD_LIBRARY_PATH"
    - "export PATH=/usr/local/musa/bin:$PATH"
    - "cd ${WORKSPACE}/${REPO_NAME}"
    - "echo 'Cloning submodules in main repository (non-recursive)...'"
    - "git submodule update --init"
    - "echo 'Entering 3rdparty/tvm and cloning its submodules...'"
    - "cd 3rdparty/tvm"
    - "git submodule update --init"
    - "echo 'Entering 3rdparty/tvm_ffi and manually cloning dlpack and libbacktrace...'"
    - "cd 3rdparty/tvm-ffi"
    - "git config submodule.3rdparty/dlpack.url git@sh-code.mthreads.com:mirror/github.com/dmlc/dlpack.git"
    - "git config submodule.3rdparty/libbacktrace.url git@sh-code.mthreads.com:mirror/github.com/ianlancetaylor/libbacktrace.git"
    - "git submodule update --init"
    - "cd ${WORKSPACE}/${REPO_NAME}"
    - "export USE_MUSA=1"
    - "export PATH=/opt/_internal/cpython-3.10.19/bin:$PATH"
    - "pip install -r requirements-dev.txt"
    - "python3 -m build --wheel -C cmake.define.USE_ALTERNATIVE_LINKER=OFF"
    - "cd dist && pip install *.whl"